// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.1";

// src/lib/mcp/tools/buscar-ordens-servico.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/buscar-ordens-servico.ts
var COLUNAS = "auvo_task_id, cliente, tecnico, data_tarefa, status_auvo, descricao, equipamento_nome, equipamento_id_serie, gc_os_codigo, gc_os_situacao, gc_os_valor_total, gc_os_data, gc_os_link, gc_orcamento_codigo, gc_orc_situacao, gc_orc_valor_total, gc_orc_data, gc_orc_link";
var buscar_ordens_servico_default = defineTool({
  name: "buscar_ordens_servico",
  title: "Buscar ordens de servi\xE7o",
  description: "Consulta o Controle de OS (tarefas do Auvo cruzadas com OS e or\xE7amentos do Gest\xE3oClick): cliente, t\xE9cnico, datas, situa\xE7\xE3o e valores.",
  inputSchema: {
    cliente: z.string().optional().describe("Nome ou parte do nome do cliente"),
    tecnico: z.string().optional().describe("Nome ou parte do nome do t\xE9cnico"),
    numero: z.string().optional().describe("N\xFAmero da OS ou do or\xE7amento no Gest\xE3oClick"),
    situacao: z.string().optional().describe("Texto da situa\xE7\xE3o da OS ou do or\xE7amento"),
    data_de: z.string().optional().describe("Data inicial no formato YYYY-MM-DD"),
    data_ate: z.string().optional().describe("Data final no formato YYYY-MM-DD"),
    limite: z.number().optional().describe("M\xE1ximo de registros retornados (padr\xE3o 25, m\xE1ximo 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limite = Math.min(Math.max(Number(input.limite) || 25, 1), 100);
    let q = supabaseForUser(ctx).from("tarefas_central").select(COLUNAS).order("data_tarefa", { ascending: false }).limit(limite);
    if (input.cliente) q = q.ilike("cliente", `%${input.cliente}%`);
    if (input.tecnico) q = q.ilike("tecnico", `%${input.tecnico}%`);
    if (input.numero) q = q.or(`gc_os_codigo.eq.${input.numero},gc_orcamento_codigo.eq.${input.numero}`);
    if (input.situacao) {
      q = q.or(`gc_os_situacao.ilike.%${input.situacao}%,gc_orc_situacao.ilike.%${input.situacao}%`);
    }
    if (input.data_de) q = q.gte("data_tarefa", input.data_de);
    if (input.data_ate) q = q.lte("data_tarefa", input.data_ate);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, registros: data ?? [] }) }],
      structuredContent: { total: data?.length ?? 0, registros: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/consultar-preventivas.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var consultar_preventivas_default = defineTool2({
  name: "consultar_preventivas",
  title: "Consultar preventivas de equipamentos",
  description: "Consulta a preventiva dos equipamentos: \xFAltima preventiva, pr\xF3xima prevista, periodicidade, criticidade e status (Em dia, Atrasada, Sem registro).",
  inputSchema: {
    cliente: z2.string().optional().describe("Nome ou parte do nome do cliente"),
    equipamento: z2.string().optional().describe("Nome do equipamento"),
    identificador: z2.string().optional().describe("S\xE9rie ou patrim\xF4nio do equipamento"),
    status: z2.string().optional().describe("Filtro pelo status da preventiva"),
    limite: z2.number().optional().describe("M\xE1ximo de registros (padr\xE3o 25, m\xE1ximo 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limite = Math.min(Math.max(Number(input.limite) || 25, 1), 100);
    let q = supabaseForUser(ctx).from("equipamento_preventiva_consolidado").select(
      "nome, identificador, cliente, categoria, marca, tipo_nome, criticidade, periodicidade, periodicidade_meses, ultima_preventiva, ultima_preventiva_tecnico, proxima_preventiva, status_preventiva, total_tarefas, equip_status"
    ).limit(limite);
    if (input.cliente) q = q.ilike("cliente", `%${input.cliente}%`);
    if (input.equipamento) q = q.ilike("nome", `%${input.equipamento}%`);
    if (input.identificador) q = q.ilike("identificador", `%${input.identificador}%`);
    if (input.status) q = q.ilike("status_preventiva", `%${input.status}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, equipamentos: data ?? [] }) }],
      structuredContent: { total: data?.length ?? 0, equipamentos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/buscar-equipamentos.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var buscar_equipamentos_default = defineTool3({
  name: "buscar_equipamentos",
  title: "Buscar equipamentos",
  description: "Lista equipamentos cadastrados (Auvo) por cliente, nome ou s\xE9rie, com marca, categoria e status.",
  inputSchema: {
    cliente: z3.string().optional().describe("Nome ou parte do nome do cliente"),
    nome: z3.string().optional().describe("Nome do equipamento"),
    identificador: z3.string().optional().describe("S\xE9rie ou patrim\xF4nio"),
    limite: z3.number().optional().describe("M\xE1ximo de registros (padr\xE3o 25, m\xE1ximo 100)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limite = Math.min(Math.max(Number(input.limite) || 25, 1), 100);
    let q = supabaseForUser(ctx).from("equipamentos_auvo").select("nome, descricao, identificador, cliente, categoria, marca, status, auvo_equipment_id").limit(limite);
    if (input.cliente) q = q.ilike("cliente", `%${input.cliente}%`);
    if (input.nome) q = q.ilike("nome", `%${input.nome}%`);
    if (input.identificador) q = q.ilike("identificador", `%${input.identificador}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, equipamentos: data ?? [] }) }],
      structuredContent: { total: data?.length ?? 0, equipamentos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/observacoes-os.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var observacoes_os_default = defineTool4({
  name: "observacoes_os",
  title: "Ler observa\xE7\xF5es de OS",
  description: "L\xEA as observa\xE7\xF5es internas registradas no Controle de OS para uma ordem de servi\xE7o, tarefa ou cliente.",
  inputSchema: {
    gc_os_codigo: z4.string().optional().describe("C\xF3digo da OS no Gest\xE3oClick"),
    auvo_task_id: z4.string().optional().describe("ID da tarefa no Auvo"),
    cliente: z4.string().optional().describe("Nome ou parte do nome do cliente"),
    limite: z4.number().optional().describe("M\xE1ximo de registros (padr\xE3o 20, m\xE1ximo 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limite = Math.min(Math.max(Number(input.limite) || 20, 1), 50);
    let q = supabaseForUser(ctx).from("os_observacoes").select("*").order("created_at", { ascending: false }).limit(limite);
    if (input.gc_os_codigo) q = q.eq("gc_os_codigo", input.gc_os_codigo);
    if (input.auvo_task_id) q = q.eq("auvo_task_id", input.auvo_task_id);
    if (input.cliente) q = q.ilike("cliente", `%${input.cliente}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ total: data?.length ?? 0, observacoes: data ?? [] }) }],
      structuredContent: { total: data?.length ?? 0, observacoes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/consultar-agenda.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var consultar_agenda_default = defineTool5({
  name: "consultar_agenda",
  title: "Consultar agenda da equipe",
  description: "Consulta os agendamentos da equipe por per\xEDodo, t\xE9cnico ou cliente, com dura\xE7\xE3o planejada, origem (Auvo, contrato ou manual) e status.",
  inputSchema: {
    data_de: z5.string().optional().describe("Data inicial no formato YYYY-MM-DD"),
    data_ate: z5.string().optional().describe("Data final no formato YYYY-MM-DD"),
    colaborador: z5.string().optional().describe("Nome ou parte do nome do t\xE9cnico"),
    cliente: z5.string().optional().describe("Nome ou parte do nome do cliente"),
    limite: z5.number().optional().describe("M\xE1ximo de registros (padr\xE3o 50, m\xE1ximo 200)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const limite = Math.min(Math.max(Number(input.limite) || 50, 1), 200);
    let q = supabaseForUser(ctx).from("agenda_agendamentos").select(
      "data, hora_inicio, hora_fim, colaborador_nome, cliente, descricao, duracao_planejada_minutos, origem, status, gc_os_codigo, gc_orcamento_codigo, auvo_task_id"
    ).order("data", { ascending: true }).limit(limite);
    if (input.data_de) q = q.gte("data", input.data_de);
    if (input.data_ate) q = q.lte("data", input.data_ate);
    if (input.colaborador) q = q.ilike("colaborador_nome", `%${input.colaborador}%`);
    if (input.cliente) q = q.ilike("cliente", `%${input.cliente}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const minutos = (data ?? []).reduce((acc, r) => acc + (Number(r.duracao_planejada_minutos) || 0), 0);
    const payload = { total: data?.length ?? 0, horas_planejadas: Number((minutos / 60).toFixed(2)), agendamentos: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bysljmkwkxrkovsaodxv";
var mcp_default = defineMcp({
  name: "auvo-gc-sync",
  title: "Auvo GC Sync",
  version: "0.1.0",
  instructions: "Ferramentas de leitura da opera\xE7\xE3o Auvo + Gest\xE3oClick: ordens de servi\xE7o e or\xE7amentos (Controle de OS), preventivas de equipamentos, cadastro de equipamentos, observa\xE7\xF5es internas de OS e agenda da equipe. Cada usu\xE1rio acessa somente os dados permitidos pela sua conta.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [buscar_ordens_servico_default, consultar_preventivas_default, buscar_equipamentos_default, observacoes_os_default, consultar_agenda_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
